# Configuration for YouTube automation pipeline

# Translation engines
translate:
  default_engine: claude

  claude:
    model: claude-sonnet-4-5-20250929  # Sonnet 4.5 (latest)
    max_tokens: 4000
    temperature: 0.3        # Default for general content
    temperature_tech: 0.1   # For technical/factual content
    timeout: 60
    retries: 3
    backoff: 2
    log_path: logs/translate.log
    chunk_size: 2000  # Characters per chunk for long texts

  argos:
    src: ko
    tgt: en
    max_len: 160
    max_tokens: 40

  glossary_path: assets/glossary.csv

# TTS settings
tts:
  engine: piper  # Default: Piper TTS (offline)
  default_preset: onyx_natural  # Use onyx_natural by default (for openai)
  sample_rate: 22050
  normalize: true
  crossfade_ms: 30
  fallback_engine: piper   # Fallback to Piper if OpenAI fails

  # Piper settings (legacy/fallback)
  piper:
    voice_model_path: assets/voices/en_GB-northern_english_male-medium.onnx
    pause:
      short: 0.30
      medium: 0.60
      long: 1.00

# OpenAI TTS settings
openai:
  enabled: true
  tts:
    model: "${OPENAI_TTS_MODEL:-tts-1}"
    voice: "${OPENAI_TTS_VOICE:-onyx}"
    format: "${OPENAI_TTS_FORMAT:-wav}"
    speed: "${OPENAI_TTS_SPEED:-1.0}"
    pause_profile: "${OPENAI_TTS_PAUSE_PROFILE:-natural}"
    pause_short: "${OPENAI_TTS_PAUSE_SHORT:-0.25}"
    pause_medium: "${OPENAI_TTS_PAUSE_MEDIUM:-0.50}"
    pause_long: "${OPENAI_TTS_PAUSE_LONG:-0.80}"
    chunk_chars: 1600  # Max characters per synthesis chunk

# File paths
paths:
  work_dir: "work"
  output_dir: "output"
  assets_dir: "assets"
  piper_exec: "${PIPER_EXEC:-piper}"
  piper_model: "${PIPER_MODEL:-$HOME/piper_models/en_US-amy-medium.onnx}"
  ffmpeg_exec: "ffmpeg"

# Processing options
options:
  voice: "en_US-amy"
  speech_rate: 1.0
  audio_sample_rate: 22050

# Language settings
language:
  source: "ko"
  target: "en"

# SEO settings
seo:
  title_prefix: ""
  tags:
    - Korean
    - English
    - Translation
    - TTS
    - Video

# Video settings
video:
  width: 1920
  height: 1080
  fps: 30
  background_color: "#000000"

# Publishing settings (optional)
publish:
  wordpress: false
  youtube: false