# Configuration for YouTube automation pipeline
translator: argos    # argos | google
use_api: false      # Use offline translation by default

# TTS settings  
tts:
  engine: piper     # piper | elevenlabs
  voice: "en_US-amy"

# File paths
paths:
  work_dir: "work"
  output_dir: "output"
  assets_dir: "assets"
  piper_exec: "${PIPER_EXEC:-piper}"
  piper_model: "${PIPER_MODEL:-$HOME/piper_models/en_US-amy-medium.onnx}"
  ffmpeg_exec: "ffmpeg"

# Processing options
options:
  voice: "en_US-amy"
  speech_rate: 1.0
  audio_sample_rate: 22050

# Language settings
language:
  source: "ko"
  target: "en"

# Video settings
video:
  width: 1920
  height: 1080
  fps: 30
  background_color: "#000000"

# Publishing settings (optional)
publish:
  wordpress: false
  youtube: false